source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'RESideMenu', '~> 4.0.7'
pod 'RaptureXML'
pod 'DejalActivityView'
pod 'AFNetworking', '~> 2.0'
pod 'JMStaticContentTableViewController', '~> 0.3.1'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'GooglePlus-iOS-SDK'
pod 'RMMapper'